# Firewall Rules Configuration - Global Region Support
# This file defines network access rules for test VMs

global_rules:
  # SSH Access - Restricted to specific IPs in production
  - name: "allow-ssh"
    direction: "ingress"
    protocol: "tcp"
    port: 22
    source_ranges:
      - "0.0.0.0/0"  # TODO: Restrict to known IPs in production
    description: "SSH access for VM management"

  # Test Runner API Access
  - name: "allow-test-runner"
    direction: "ingress"
    protocol: "tcp"
    port: 5000
    source_ranges:
      - "0.0.0.0/0"
    description: "Test Runner webhook and API access"

  # API Server Access
  - name: "allow-api-server"
    direction: "ingress"
    protocol: "tcp"
    port: 8080
    source_ranges:
      - "0.0.0.0/0"
    description: "API Server HTTP"